const data = [
    {
        name:"Abhijeet",
        course:"Mern",
        Age:"22",
        Sex:"Male"
    },
    {
        name:"Rohit",
        course:"Mern",
        Age:"22",
        Sex:"Male"
    },
    {
        name:"Kunal",
        course:"Mern",
        Age:"22",
        Sex:"Male"
    },
    {
        name:"Yash",
        course:"Mern",
        Age:"22",
        Sex:"Male"
    },
    {
        name:"Roshan",
        course:"Mern",
        Age:"22",
        Sex:"Male"
    },
    {
        name:"Ravi",
        course:"Mern",
        Age:"22",
        Sex:"Male"
    },
    {
        name:"Ansh",
        course:"Mern",
        Age:"22",
        Sex:"Male"
    },
    {
        name:"Kittu",
        course:"Mern",
        Age:"22",
        Sex:"Male"
    },
    {
        name:"Sonam",
        course:"Mern",
        Age:"22",
        Sex:"Male"
    }
]

module.exports = data